// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: dwango/nicolive/chat/data/origin.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NicoliveOrigin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Origin:
	//
	//	*NicoliveOrigin_Chat_
	Origin        isNicoliveOrigin_Origin `protobuf_oneof:"origin"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicoliveOrigin) Reset() {
	*x = NicoliveOrigin{}
	mi := &file_dwango_nicolive_chat_data_origin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicoliveOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicoliveOrigin) ProtoMessage() {}

func (x *NicoliveOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_origin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicoliveOrigin.ProtoReflect.Descriptor instead.
func (*NicoliveOrigin) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_origin_proto_rawDescGZIP(), []int{0}
}

func (x *NicoliveOrigin) GetOrigin() isNicoliveOrigin_Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *NicoliveOrigin) GetChat() *NicoliveOrigin_Chat {
	if x != nil {
		if x, ok := x.Origin.(*NicoliveOrigin_Chat_); ok {
			return x.Chat
		}
	}
	return nil
}

type isNicoliveOrigin_Origin interface {
	isNicoliveOrigin_Origin()
}

type NicoliveOrigin_Chat_ struct {
	Chat *NicoliveOrigin_Chat `protobuf:"bytes,1,opt,name=chat,proto3,oneof"`
}

func (*NicoliveOrigin_Chat_) isNicoliveOrigin_Origin() {}

type NicoliveOrigin_Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LiveId        int64                  `protobuf:"varint,1,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicoliveOrigin_Chat) Reset() {
	*x = NicoliveOrigin_Chat{}
	mi := &file_dwango_nicolive_chat_data_origin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicoliveOrigin_Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicoliveOrigin_Chat) ProtoMessage() {}

func (x *NicoliveOrigin_Chat) ProtoReflect() protoreflect.Message {
	mi := &file_dwango_nicolive_chat_data_origin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicoliveOrigin_Chat.ProtoReflect.Descriptor instead.
func (*NicoliveOrigin_Chat) Descriptor() ([]byte, []int) {
	return file_dwango_nicolive_chat_data_origin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NicoliveOrigin_Chat) GetLiveId() int64 {
	if x != nil {
		return x.LiveId
	}
	return 0
}

var File_dwango_nicolive_chat_data_origin_proto protoreflect.FileDescriptor

var file_dwango_nicolive_chat_data_origin_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f,
	0x2e, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x0e, 0x4e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x44, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x6e, 0x69,
	0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x4e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x1f, 0x0a, 0x04,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x69, 0x76, 0x65, 0x49, 0x64, 0x42, 0x08, 0x0a,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x69, 0x6e, 0x6f, 0x73, 0x61, 0x6b, 0x69, 0x2f,
	0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x64, 0x77, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6e, 0x69, 0x63, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_dwango_nicolive_chat_data_origin_proto_rawDescOnce sync.Once
	file_dwango_nicolive_chat_data_origin_proto_rawDescData []byte
)

func file_dwango_nicolive_chat_data_origin_proto_rawDescGZIP() []byte {
	file_dwango_nicolive_chat_data_origin_proto_rawDescOnce.Do(func() {
		file_dwango_nicolive_chat_data_origin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dwango_nicolive_chat_data_origin_proto_rawDesc), len(file_dwango_nicolive_chat_data_origin_proto_rawDesc)))
	})
	return file_dwango_nicolive_chat_data_origin_proto_rawDescData
}

var file_dwango_nicolive_chat_data_origin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dwango_nicolive_chat_data_origin_proto_goTypes = []any{
	(*NicoliveOrigin)(nil),      // 0: dwango.nicolive.chat.data.NicoliveOrigin
	(*NicoliveOrigin_Chat)(nil), // 1: dwango.nicolive.chat.data.NicoliveOrigin.Chat
}
var file_dwango_nicolive_chat_data_origin_proto_depIdxs = []int32{
	1, // 0: dwango.nicolive.chat.data.NicoliveOrigin.chat:type_name -> dwango.nicolive.chat.data.NicoliveOrigin.Chat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dwango_nicolive_chat_data_origin_proto_init() }
func file_dwango_nicolive_chat_data_origin_proto_init() {
	if File_dwango_nicolive_chat_data_origin_proto != nil {
		return
	}
	file_dwango_nicolive_chat_data_origin_proto_msgTypes[0].OneofWrappers = []any{
		(*NicoliveOrigin_Chat_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dwango_nicolive_chat_data_origin_proto_rawDesc), len(file_dwango_nicolive_chat_data_origin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dwango_nicolive_chat_data_origin_proto_goTypes,
		DependencyIndexes: file_dwango_nicolive_chat_data_origin_proto_depIdxs,
		MessageInfos:      file_dwango_nicolive_chat_data_origin_proto_msgTypes,
	}.Build()
	File_dwango_nicolive_chat_data_origin_proto = out.File
	file_dwango_nicolive_chat_data_origin_proto_goTypes = nil
	file_dwango_nicolive_chat_data_origin_proto_depIdxs = nil
}
